static_sites:
  - name: brandgea-lab-dev-frontend
    rootDir: client
    buildCommand: npm run build
    staticPath: dist
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"